### ISSUE TITLE
busybox-w32

### ISSUE THREAD

**Issue by ale5000-git** [git-for-windows/7-Zip#5]
@dscho
Hi,
I wanted to write on https://github.com/git-for-windows/busybox-w32 but `Issues` aren't enabled.

I wanted to ask if you could please merge the changes from [rmyorston/busybox-w32](https://github.com/rmyorston/busybox-w32).
There are a lot of interesting changes from the last year.

**Comment by dscho** [comment]
Why not do some of the work yourself and open a PR?
