### ISSUE TITLE
I want to add "%userprofile%" to the InstallPath

### ISSUE THREAD

**Issue by heetbeet** [git-for-windows/7-Zip#7]
I want to expand [this part](https://github.com/git-for-windows/7-Zip/blob/dfe38366c6998f87971f89ae6082ee25f7d21028/CPP/7zip/Bundles/SFXSetup/SfxSetup.cpp#L245) to work with %userprofile% (or maybe even any environment variables), but I don't know how to actually retrieve environment variables in C++ (well, not without adding extra bloat like `std::`). 

My question is: are there any functionality already in the codebase to access environment variables? Where can I find it?

**Comment by dscho** [comment]
I am _guessing_ you want to imitate https://github.com/git-for-windows/7-Zip/blob/dfe38366c6998f87971f89ae6082ee25f7d21028/CPP/7zip/Bundles/SFXSetup/SfxSetup.cpp#L245-L257 to implement that feature.

And retrieving an environment variable is as easy as calling [`GetEnvironmentVariable()`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getenvironmentvariable). There is one precedent for this in the current code: https://github.com/git-for-windows/7-Zip/blob/dfe38366c6998f87971f89ae6082ee25f7d21028/C/Util/7zipInstall/7zipInstall.c#L1048

**Comment by heetbeet** [comment]
Thanks for the info
